services:

  local-reverse-proxy:
    container_name: reverse-proxy
    restart: always
    build:
      context: ./
      dockerfile: /docker/Dockerfile
    ports:
      - "80:80"
      - "443:443"

    networks:
      default:
        aliases:
          - crazyx13th.github.local
